export const ticketTypes = {
    INGRESO: 'INGRESO',
    EXTRACCION: 'EXTRACCION',
    SUPERVISION_ENTRADA: 'SUPERVISION_ENTRADA',
    SUPERVISION_SALIDA: 'SUPERVISION_SALIDA',
    PRESTAMO: 'PRESTAMO',
    DEVOLUCION: 'DEVOLUCION',
}